[package]
name = "sia-vfs"
version = "0.1.0"
edition = "2024"

[features]
default = ["indexd", "lz4", "renterd", "zstd"]
indexd = ["sia-io/indexd"]
lz4 = ["dep:lz4_flex"]
mock = ["sia-io/mock"]
renterd = ["sia-io/renterd"]
zstd = ["dep:zstd"]

[dependencies]
sia-io = { path = "../sia-io", default-features = false }

async-trait = { workspace = true }
blake3 = "1.8"
bon = { workspace = true }
bytemuck = { version = "1.25", features = ["derive"] }
bytes = { workspace = true }
bytesize = { workspace = true }
chrono = { workspace = true }
derive-where = { workspace = true, features = ["zeroize", "serde"] }
flatbuffers = "=25.12.19"
lz4_flex = { version = "0.13", optional = true }
elsa = "1.11"
futures-channel = "0.3"
futures-io = { workspace = true }
futures-util = { workspace = true, features = ["io"] }
moka = { workspace = true, features = ["future"] }
sqlx = { workspace = true, features = ["runtime-tokio", "tls-rustls", "sqlite", "migrate"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }
tracing = { workspace = true }
twox-hash = { workspace = true, features = ["xxhash3_64", "std"] }
typed-path = { workspace = true }
uuid = { version = "1.23", features = ["v7", "bytemuck"] }
yoke = "0.8"
zstd = { version = "0.13", optional = true }

[dev-dependencies]
sia-vfs = { path = ".", features = ["mock"] }

anyhow = { workspace = true }
tempfile = "3"
tokio = { workspace = true, features = ["full"] }

[build-dependencies]
anyhow = { workspace = true }
flatbuffers-build = { version = "=0.2.4", features = ["vendored"] }
sqlx = { workspace = true, features = ["runtime-tokio", "tls-rustls", "sqlite", "migrate", "chrono"] }
tokio = { workspace = true, features = ["full"] }
