include "content_id.fbs";

namespace entity;

table File {
  len: uint64;
  blob_id: common.ContentId (required);
}

struct DirectoryEntry {
  id: common.Uuid;
  revision: common.ContentId;
}

table Directory {
  entries: [DirectoryEntry];
}

union EntityBody { File, Directory }

table Entity {
  id: common.Uuid (required);
  name: string (required);
  created: int64;
  last_modified: int64;
  body: EntityBody (required);
}

namespace blob;

struct Chunk {
  offset: uint64;
  len: uint64;
  chunk_id: common.ContentId;
  chunk_offset: uint64;
}

table Blob {
    len: uint64;
    chunks: [Chunk];
}

namespace commit;

table Commit {
    entity_id: common.Uuid (required);
    entity_rev: common.ContentId (required);
    created: int64;
    count: uint64;
    prev_id: common.ContentId (required);
}