[package]
name = "sia-io"
version = "0.1.0"
edition = "2024"

[features]
renterd = ["dep:chrono", "dep:reqwest", "dep:serde_json"]
indexd = ["dep:sia_storage", "dep:tokio", "dep:tokio-util"]

[dependencies]
async-trait = "0.1"
bon = "3.9"
bytesize = "2.3"
chrono = { version = "0.4", features = ["serde"], optional = true }
ct-codecs = "1.1"
derive-where = { version = "1.6", features = ["zeroize", "serde"] }
futures-io = "0.3"
futures-util = { version = "0.3", features = ["io"] }
indexmap = "2"
maybe-owned = "0.3"
mime = "0.3"
moka = { version = "0.12", features = ["future"] }
ouroboros = "0.18"
papaya = "0.2"
reqwest = { version = "0.13", features = ["stream", "json", "query"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }
sia_storage = { version = "0.6", optional = true }
thiserror = "2.0"
tokio = { version = "1.51", features = ["default"], optional = true }
tokio-util = { version = "0.7", features = ["compat"], optional = true }
typed-path = "0.12"
zeroize = { version = "1.8", features = ["serde", "derive"] }

[dev-dependencies]
anyhow = "1.0"
dotenv = "0.15"
tokio = { version = "1.51", features = ["full"] }