[package]
name = "sia-io"
version = "0.1.0"
edition = "2024"

[features]
default = ["indexd", "renterd"]
indexd = ["dep:sia_storage", "dep:tokio", "dep:tokio-util"]
renterd = ["dep:chrono", "dep:reqwest", "dep:serde_json"]
mock = []

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bimap = { workspace = true }
bon = { workspace = true }
bytes = { workspace = true, features = ["serde"] }
bytesize = { workspace = true }
chrono = { workspace = true, features = ["serde"], optional = true }
ct-codecs = { workspace = true }
derive-where = { workspace = true, features = ["zeroize", "serde"] }
futures-io = { workspace = true }
futures-util = { workspace = true, features = ["io"] }
indexmap = "2"
itertools = { workspace = true }
maybe-owned = "0.3"
mime = "0.3"
moka = { workspace = true, features = ["future"] }
ouroboros = "0.18"
papaya = "0.2"
parking_lot = { workspace = true }
reqwest = { version = "0.13", features = ["stream", "json", "query"], optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }
sia_storage = { version = "0.6", optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["default"], optional = true }
tokio-util = { version = "0.7", features = ["compat"], optional = true }
tracing = { workspace = true }
twox-hash = { workspace = true, features = ["xxhash3_64"] }
typed-path = { workspace = true }
zeroize = { workspace = true, features = ["serde", "derive"] }

[dev-dependencies]
anyhow = { workspace = true }
dotenv = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing-subscriber = { workspace = true }